### ISSUE TITLE
Add a more understandable message when the "family" does not exist

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/string2vocabulary#1]
When [`getVocabularyCategory`](https://github.com/DOREMUS-ANR/string2vocabulary/blob/644c2d4d9a1d62eb1c36f3d41c42d8cb7090f614/src/main/java/org/doremus/string2vocabulary/VocabularyManager.java#L153) returns `null`, it throws a `NullPointerException`.

Add a check and a more clear message ("The family <aFamily> is not available").

**Comment by rtroncy** [comment]
Use the term 'Concept Scheme' rather than 'family' ?

**Comment by pasqLisena** [comment]
It is actually a "family" of ConceptSchemes.
I.e. the family "mop" includes "mop-mimo", "mop-iaml", "mop-rameau", ...
